import fs from "node:fs";
import { randomBytes } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { stagingEnv } from "../../scripts/staging-env.mjs";
const config = stagingEnv();

test("synthetic clinic: eight-step setup, patient CRUD, private PDF, notes, appointment and tenant boundaries", async ({page,context,request}) => {
  test.setTimeout(240000);
  const headers: Record<string,string> = config.env.STAGING_PREVIEW_BYPASS_SECRET ? {"x-vercel-protection-bypass":config.env.STAGING_PREVIEW_BYPASS_SECRET} : {};
  if (config.env.STAGING_PREVIEW_BYPASS_SECRET) await context.route(`${config.origin}/**`, route => route.continue({headers:{...route.request().headers(),...headers}}));
  const marker = await request.get("/api/staging/status",{headers}); const status = await marker.json();
  expect(status.environment === "staging" && status.supabaseProjectRef === config.ref).toBe(true);
  const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}};
  const admin=createClient(config.env.NEXT_PUBLIC_SUPABASE_URL,config.env.SUPABASE_SERVICE_ROLE_KEY,options);
  const owner=createClient(config.env.NEXT_PUBLIC_SUPABASE_URL,config.publicKey,options);
  const email=`pilot-${Date.now()}@voxa-qa.invalid`,password=randomBytes(32).toString("base64url");
  // Admin-confirmed fixture only: no confirmation mail is sent to an invented address.
  const created=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:"Operator Pilot Fictiv"}});
  expect(Boolean(created.error)).toBe(false);
  const actor={ref:config.ref,email,password,userId:created.data.user!.id,createdAt:new Date().toISOString()};
  fs.writeFileSync(".staging-deploy/pilot-actor.local.json",JSON.stringify(actor));
  const browserErrors:string[]=[];page.on("pageerror",error=>browserErrors.push(error.message));
  const signIn=async()=>{await page.goto("/login");await page.getByLabel("Utilizator").fill(email);await page.getByLabel("Parolă",{exact:true}).fill(password);await page.getByRole("button",{name:"Conectare",exact:true}).click();};
  await signIn(); await expect(page).toHaveURL(/\/onboarding/);
  await page.getByLabel("Denumirea organizației").fill("Clinica Pilot · date fictive");await page.getByLabel("Prima locație").fill("Oradea Pilot");await page.getByRole("button",{name:"Creează spațiul de lucru"}).click();
  await expect(page.getByRole("heading",{name:"Clinica",exact:true})).toBeVisible();await page.getByLabel("Email clinică",{exact:true}).fill("clinic@voxa-qa.invalid");await page.getByRole("button",{name:"Continuă",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Locații",exact:true})).toBeVisible();await page.getByLabel("Oraș",{exact:true}).fill("Oradea");await page.getByRole("button",{name:"Continuă",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Program",exact:true})).toBeVisible();await page.getByRole("button",{name:"Continuă",exact:true}).click();
  await page.getByRole("button",{name:"Adaugă serviciu",exact:true}).click();let record=page.locator(".setup-record").first();await record.getByLabel("Denumire serviciu").fill("Consultație Pilot");await record.getByLabel("Preț (RON)").fill("200");await page.getByRole("button",{name:"Continuă",exact:true}).click();
  await page.getByRole("button",{name:"Adaugă medic",exact:true}).click();record=page.locator(".setup-record").first();await record.getByLabel("Prenume",{exact:true}).fill("Ana");await record.getByLabel("Nume",{exact:true}).fill("Pilot");await record.getByRole("checkbox",{name:"Consultație Pilot · Oradea Pilot",exact:true}).check();await page.getByRole("button",{name:"Continuă",exact:true}).click();
  await page.getByRole("button",{name:"Adaugă cabinet",exact:true}).click();await page.getByLabel("Denumire cabinet").fill("Cabinet Pilot");await page.getByRole("button",{name:"Continuă",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Echipă",exact:true})).toBeVisible();await page.getByRole("button",{name:"Continuă",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Finalizare",exact:true})).toBeVisible();await page.reload();await expect(page.getByRole("heading",{name:"Finalizare",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Finalizează configurarea",exact:true}).click();await page.getByRole("link",{name:"Intră în spațiul de lucru",exact:true}).click();await expect(page.getByRole("heading",{name:"Spațiul de lucru",exact:true})).toBeVisible();
  const base=new URL(page.url()).pathname,clinicId=base.split("/")[2];
  expect(/^[a-f0-9-]{36}$/.test(clinicId)).toBe(true);
  expect(Boolean((await owner.auth.signInWithPassword({email,password})).error)).toBe(false);
  const membership=await owner.from("clinic_memberships").select("organization_id,role").eq("clinic_id",clinicId);expect(membership.error).toBeNull();expect(membership.data?.length).toBe(1);
  const organizationId=membership.data![0].organization_id;
  fs.writeFileSync(".staging-deploy/pilot-actor.local.json",JSON.stringify({...actor,clinicId,organizationId}));
  console.log("Pilot: complete guided setup and persisted clinic configuration");
  await page.goto(`${base}/patients`);await page.getByRole("button",{name:"Adaugă pacient",exact:true}).first().click();let dialog=page.getByRole("dialog");
  const name="Pacient Fictiv Pilot";
  await dialog.getByLabel("Nume și prenume").fill(name);await dialog.getByLabel("Identificator intern").fill("PILOT-001");await dialog.getByRole("button",{name:"Creează înregistrarea",exact:true}).click();await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();
  const profile=new URL(page.url()).pathname,patientId=profile.split("/").pop()!;
  await page.getByRole("button",{name:"Editează",exact:true}).click();dialog=page.getByRole("dialog");await dialog.getByLabel("Note administrative",{exact:true}).fill("Date complet fictive pentru verificarea pilotului.");await dialog.getByRole("button",{name:"Salvează modificările",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.reload();await expect(page.getByText("Date complet fictive pentru verificarea pilotului.",{exact:true})).toBeVisible();
  await page.getByLabel("Conținut notă").fill("Notă clinică fictivă de acceptanță.");await page.getByRole("button",{name:"Adaugă nota",exact:true}).click();await expect(page.getByText("Notă clinică fictivă de acceptanță.",{exact:true})).toBeVisible();
  await page.getByRole("navigation",{name:"Secțiuni profil pacient"}).getByRole("link",{name:"Documente",exact:true}).click();await page.getByRole("button",{name:"Încarcă document",exact:true}).click();dialog=page.getByRole("dialog");await dialog.getByLabel("Titlu",{exact:true}).fill("PDF Pilot Fictiv");await dialog.getByLabel("Fișier",{exact:true}).setInputFiles(".staging-deploy/fixtures/voxa-synthetic-b.pdf");await dialog.getByRole("button",{name:"Încarcă",exact:true}).click();
  await expect(page.getByText("PDF Pilot Fictiv",{exact:true})).toBeVisible();
  const documents=await owner.from("patient_documents").select("id,object_path").eq("clinic_id",clinicId).eq("patient_id",patientId);expect(documents.error).toBeNull();expect(documents.data?.length).toBe(1);
  const document=documents.data![0];const downloaded=await owner.storage.from("voxa-medical").download(document.object_path);expect(Boolean(downloaded.error)).toBe(false);expect((await downloaded.data!.arrayBuffer()).byteLength>0).toBe(true);
  const downloadResponse=await page.request.get(`/api/clinics/${clinicId}/documents/${document.id}/download`,{headers,maxRedirects:0});expect(downloadResponse.status()).toBe(307);
  const day=new Date();day.setUTCDate(day.getUTCDate()+2);while([0,6].includes(day.getUTCDay()))day.setUTCDate(day.getUTCDate()+1);const date=day.toISOString().slice(0,10),dateRo=date.split("-").reverse().join(".");
  await page.goto(`${base}/calendar?view=day&date=${date}`);await page.getByRole("button",{name:"Programare nouă",exact:true}).click();dialog=page.getByRole("dialog");await dialog.getByLabel("Caută pacient").fill(name);await dialog.getByRole("button",{name:new RegExp(name)}).click();await dialog.getByLabel("Serviciu",{exact:true}).selectOption({label:"Consultație Pilot"});await dialog.getByLabel("Medic",{exact:true}).selectOption({label:"Ana Pilot"});await dialog.getByLabel("Data",{exact:true}).fill(dateRo);await page.keyboard.press("Tab");await expect(dialog.locator(".slot-picker button").first()).toBeVisible();await dialog.locator(".slot-picker button").first().click();await dialog.getByRole("button",{name:"Creează programarea",exact:true}).click();
  await expect(page.getByRole("button",{name:new RegExp(name)})).toBeVisible();await page.reload();await page.getByRole("button",{name:new RegExp(name)}).click();dialog=page.getByRole("dialog");await dialog.getByRole("button",{name:"Confirmă",exact:true}).click();await expect(page.getByText("Status actualizat: Confirmă.",{exact:true})).toBeVisible();
  console.log("Pilot: patient create/edit, clinical note, private PDF, appointment create/confirm and refresh");
  const actors=JSON.parse(fs.readFileSync(".staging-actors.local.json","utf8"));const outsider=createClient(config.env.NEXT_PUBLIC_SUPABASE_URL,config.publicKey,options);expect(Boolean((await outsider.auth.signInWithPassword(actors.a)).error)).toBe(false);
  const foreign=await outsider.from("patients").select("id").eq("id",patientId);expect(foreign.error).toBeNull();expect(foreign.data).toEqual([]);expect(Boolean((await outsider.storage.from("voxa-medical").download(document.object_path)).error)).toBe(true);expect(Boolean((await outsider.rpc("authorize_document_download",{cid:clinicId,document_id:document.id})).error)).toBe(true);
  await page.goto(profile);await page.getByRole("button",{name:"Arhivează",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Confirmă arhivarea",exact:true}).click();await expect(page).toHaveURL(`${config.origin}${base}/patients`);await page.goto(profile);await page.getByRole("button",{name:"Restaurează",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Confirmă restaurarea",exact:true}).click();await expect(page.getByRole("button",{name:"Editează",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Deconectare",exact:true}).click();await expect(page).toHaveURL(/\/login/);await signIn();await expect(page).not.toHaveURL(/\/login/);await page.goto(`${base}/calendar?view=day&date=${date}`);await expect(page.getByRole("button",{name:new RegExp(name)})).toBeVisible();
  expect(browserErrors).toEqual([]);
  fs.writeFileSync(".staging-deploy/pilot-acceptance.receipt.json",JSON.stringify({ref:config.ref,clinicId,organizationId,patientId,documentId:document.id,verifiedAt:new Date().toISOString(),onboarding:true,patientCrud:true,notes:true,privatePdf:true,appointments:true,foreignTenantDenied:true,sessionPersistence:true}));
  await owner.auth.signOut({scope:"local"});await outsider.auth.signOut({scope:"local"});
  console.log("PASS: hosted synthetic clinic pilot completed, including archive/restore, normal re-login and cross-tenant file/data denial.");
});
