"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarCheck, Check, Clock3, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input, Select } from "@/components/ui/form";
import type { PublicCatalog, PublicSlot } from "./model";

type PatientData = { name: string; phone: string; email: string; notes: string; consent: boolean; website: string };
const emptyPatient: PatientData = { name: "", phone: "", email: "", notes: "", consent: false, website: "" };

export function BookingWidget({ catalog, preselectedService = "", preselectedDoctor = "", compact = false }: { catalog: PublicCatalog; preselectedService?: string; preselectedDoctor?: string; compact?: boolean }) {
  const validService = catalog.services.some((service) => service.id === preselectedService) ? preselectedService : "";
  const validDoctor = catalog.doctors.some((doctor) => doctor.id === preselectedDoctor && (!validService || doctor.service_ids.includes(validService))) ? preselectedDoctor : "";
  const [step,setStep]=useState(validService?2:1); const [speciality,setSpeciality]=useState(""); const [service,setService]=useState(validService); const [doctor,setDoctor]=useState(validDoctor); const [date,setDate]=useState(""); const [slots,setSlots]=useState<PublicSlot[]>([]); const [slot,setSlot]=useState<PublicSlot|null>(null); const [patient,setPatient]=useState<PatientData>(emptyPatient); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState<{id:string;start:string}|null>(null); const startedAt=useRef(0);
  const selectedService=catalog.services.find((item)=>item.id===service); const selectedDoctor=catalog.doctors.find((item)=>item.id===(doctor||slot?.doctor_id));
  const services=useMemo(()=>speciality?catalog.services.filter((item)=>item.speciality_ids.includes(speciality)):catalog.services,[catalog.services,speciality]);
  const doctors=useMemo(()=>service?catalog.doctors.filter((item)=>item.service_ids.includes(service)):[],[catalog.doctors,service]);
  const today=new Intl.DateTimeFormat("sv-SE",{timeZone:catalog.clinic.timezone}).format(new Date());
  const maxDate=useMemo(()=>{const value=new Date(`${today}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+180);return value.toISOString().slice(0,10);},[today]);
  const slotRequest=useRef<AbortController|null>(null);
  const loadSlots=useCallback(async(silent=false)=>{
    if(!service||!date)return;
    slotRequest.current?.abort();
    const controller=new AbortController();slotRequest.current=controller;
    if(!silent){setLoading(true);setError("");setSlots([]);}
    const params=new URLSearchParams({clinic:catalog.clinic.slug,service,date});if(doctor)params.set("doctor",doctor);
    try{
      const response=await fetch(`/api/public/availability?${params}`,{cache:"no-store",signal:controller.signal});
      const body=await response.json();
      if(controller.signal.aborted)return;
      if(!response.ok)throw new Error(body.error);
      setSlots(body as PublicSlot[]);setSlot(current=>current&&(body as PublicSlot[]).some(item=>item.start_at===current.start_at)?current:null);
    }catch(cause){if(!controller.signal.aborted&&!silent)setError(cause instanceof Error?cause.message:"Disponibilitatea nu a putut fi verificată.");}
    finally{if(!controller.signal.aborted&&!silent)setLoading(false);}
  },[catalog.clinic.slug,date,doctor,service]);
  useEffect(()=>{if(step!==3||!date||!service)return;const initial=setTimeout(()=>loadSlots(),0);const timer=setInterval(()=>loadSlots(true),30_000);return()=>{clearTimeout(initial);clearInterval(timer);slotRequest.current?.abort();};},[step,date,service,doctor,loadSlots]);
  async function submit(){if(!slot||!selectedService)return;setLoading(true);setError("");try{const response=await fetch("/api/public/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clinic:catalog.clinic.slug,service_id:selectedService.id,doctor_id:doctor||slot.doctor_id,start_at:slot.start_at,...patient,started_at:startedAt.current})});const body=await response.json();if(!response.ok){if(response.status===409){await loadSlots(true);setStep(3);setSlot(null);}throw new Error(body.error);}setSuccess({id:body.appointment_id,start:body.start_at});setStep(6);}catch(cause){setError(cause instanceof Error?cause.message:"Programarea nu a putut fi înregistrată.");}finally{setLoading(false);}}
  function next(){if(!startedAt.current)startedAt.current=Date.now();setError("");if(step===1&&!service)return setError("Selectați un serviciu.");if(step===3&&!slot)return setError("Selectați un interval disponibil.");if(step===4&&(!patient.name.trim()||(!patient.phone.replace(/\D/g,"")&& !patient.email)||!patient.consent))return setError("Completați numele, telefonul sau emailul și acordul pentru programare.");if(step<=2){setSlots([]);setSlot(null);}setStep((value)=>Math.min(5,value+1));}
  if(success)return <div className="booking-success"><span><CalendarCheck size={28}/></span><p className="booking-kicker">PROGRAMARE ÎNREGISTRATĂ</p><h1>Vă așteptăm la {catalog.clinic.name}</h1><p>Programarea pentru <strong>{selectedService?.name}</strong> este înregistrată pentru {new Intl.DateTimeFormat("ro-RO",{timeZone:catalog.clinic.timezone,dateStyle:"long",timeStyle:"short"}).format(new Date(success.start))}.</p><small>Referință: {success.id.slice(0,8).toUpperCase()}</small></div>;
  return <div className={`booking-widget ${compact?"is-compact":""}`}>
    <header className="booking-header"><div><p className="booking-kicker">PROGRAMARE ONLINE</p><h1>{catalog.clinic.name}</h1><p><MapPin size={14}/>{catalog.clinic.address||"Locație medicală"}</p></div><div className="booking-progress" aria-label={`Pasul ${step} din 5`}><strong>0{step}</strong><span>/ 05</span></div></header>
    <div className="booking-steps" aria-hidden>{[1,2,3,4,5].map((value)=><span key={value} className={value<=step?"active":""}/>)}</div>
    <main className="booking-body">
      {step===1&&<section><p className="booking-step-label">PASUL 1</p><h2>Alegeți serviciul</h2><p className="muted">Selectați specialitatea pentru a restrânge lista, apoi serviciul dorit.</p>{catalog.specialities.length>0&&<Field label="Specialitate"><Select value={speciality} onChange={(event)=>{setSpeciality(event.target.value);setService("");setDoctor("");}}><option value="">Toate specialitățile</option>{catalog.specialities.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>}<div className="booking-choice-list">{services.map((item)=><button type="button" key={item.id} className={service===item.id?"selected":""} onClick={()=>{setService(item.id);setDoctor("");}}><span><strong>{item.name}</strong><small>{item.category||"Serviciu medical"} · {item.duration_minutes} min</small></span>{item.price!=null&&<b>{item.price} RON</b>}<Check size={17}/></button>)}</div></section>}
      {step===2&&<section><p className="booking-step-label">PASUL 2</p><h2>Alegeți medicul</h2><p className="muted">Puteți permite sistemului să aloce automat primul medic disponibil.</p><div className="booking-choice-list"><button type="button" className={doctor===""?"selected":""} onClick={()=>setDoctor("")}><span><strong>Primul medic disponibil</strong><small>Recomandat pentru cel mai apropiat interval</small></span><Check size={17}/></button>{doctors.map((item)=><button type="button" key={item.id} className={doctor===item.id?"selected":""} onClick={()=>setDoctor(item.id)}><span><strong>{item.name}</strong><small>Medic eligibil pentru serviciul selectat</small></span><Check size={17}/></button>)}</div></section>}
      {step===3&&<section><p className="booking-step-label">PASUL 3</p><h2>Alegeți data și ora</h2><Field label="Data programării"><Input type="date" min={today} max={maxDate} value={date} onChange={(event)=>{slotRequest.current?.abort();setDate(event.target.value);setSlots([]);setSlot(null);setLoading(Boolean(event.target.value));}}/></Field>{loading?<div className="booking-loading">Se verifică toate resursele necesare…</div>:date&&slots.length===0?<div className="booking-empty"><Clock3 size={22}/><strong>Nu există intervale disponibile</strong><span>Alegeți o altă zi sau un alt medic.</span></div>:<div className="public-slot-grid">{slots.map((item)=><button type="button" key={item.start_at} className={slot?.start_at===item.start_at?"selected":""} onClick={()=>setSlot(item)}>{new Intl.DateTimeFormat("ro-RO",{timeZone:catalog.clinic.timezone,hour:"2-digit",minute:"2-digit"}).format(new Date(item.start_at))}</button>)}</div>}<p className="freshness-note">Disponibilitatea se actualizează automat. Intervalul este verificat din nou la confirmare.</p></section>}
      {step===4&&<section><p className="booking-step-label">PASUL 4</p><h2>Date de contact</h2><div className="booking-form-grid"><Field label="Nume și prenume"><Input autoComplete="name" required value={patient.name} onChange={(e)=>setPatient({...patient,name:e.target.value})}/></Field><Field label="Telefon"><Input autoComplete="tel" value={patient.phone} onChange={(e)=>setPatient({...patient,phone:e.target.value})}/></Field><Field label="Email"><Input type="email" autoComplete="email" value={patient.email} onChange={(e)=>setPatient({...patient,email:e.target.value})}/></Field><Field label="Observații pentru recepție"><textarea className="input textarea" rows={3} maxLength={1000} value={patient.notes} onChange={(e)=>setPatient({...patient,notes:e.target.value})}/></Field></div><label className="honeypot" aria-hidden>Website<Input tabIndex={-1} autoComplete="off" value={patient.website} onChange={(e)=>setPatient({...patient,website:e.target.value})}/></label><label className="booking-consent"><input type="checkbox" checked={patient.consent} onChange={(e)=>setPatient({...patient,consent:e.target.checked})}/><span>Sunt de acord ca datele introduse să fie folosite pentru înregistrarea și administrarea acestei programări.</span></label></section>}
      {step===5&&<section><p className="booking-step-label">PASUL 5</p><h2>Verificați programarea</h2><dl className="booking-review"><div><dt>Locație</dt><dd>{catalog.clinic.name}</dd></div><div><dt>Serviciu</dt><dd>{selectedService?.name}</dd></div><div><dt>Medic</dt><dd>{selectedDoctor?.name||"Alocare automată"}</dd></div><div><dt>Data și ora</dt><dd>{slot&&new Intl.DateTimeFormat("ro-RO",{timeZone:catalog.clinic.timezone,dateStyle:"full",timeStyle:"short"}).format(new Date(slot.start_at))}</dd></div><div><dt>Pacient</dt><dd>{patient.name}</dd></div><div><dt>Contact</dt><dd>{patient.phone||patient.email}</dd></div></dl><div className="booking-security-note">Intervalul și toate resursele medicale vor fi reverificate în momentul confirmării.</div></section>}
      {error&&<p className="booking-error" role="alert">{error}</p>}
    </main>
    <footer className="booking-footer">{step>1&&<Button variant="ghost" onClick={()=>{setError("");setStep((value)=>value-1);}}><ArrowLeft size={16}/>Înapoi</Button>}<span/>{step<5?<Button onClick={next}>Continuă<ArrowRight size={16}/></Button>:<Button disabled={loading} onClick={submit}>{loading?"Se confirmă…":"Confirmă programarea"}</Button>}</footer>
  </div>;
}
