import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "node:fs";
import { callerQuery, ids, migratedDatabase } from "./support/database";
import { SIGNED_DOWNLOAD_TTL_SECONDS } from "../src/lib/medical-storage";

let db:PGlite; const f:Record<string,string>={};
const patientUser="10000000-0000-4000-8000-000000000020",otherPatientUser="10000000-0000-4000-8000-000000000021";
async function one<T>(uid:string,expression:string,args:unknown[]=[]){const {rows}=await callerQuery<{value:T}>(db,uid,`select ${expression} value`,args);return rows[0].value;}
async function anon<T>(expression:string,args:unknown[]=[]){return db.transaction(async tx=>{await tx.exec("set local role anon");const {rows}=await tx.query<{value:T}>(`select ${expression} value`,args);return rows[0]?.value;});}

beforeAll(async()=>{db=await migratedDatabase();await db.exec(readFileSync("supabase/seed-core.sql","utf8"));
 const patient=(await db.query<{id:string}>("select id from public.patients where clinic_id=$1 order by created_at limit 2",[ids.a])).rows;f.patient=patient[0].id;f.otherPatient=patient[1].id;
 f.clinicBPatient=(await db.query<{id:string}>("select id from public.patients where clinic_id=$1 limit 1",[ids.b])).rows[0].id;
 f.service=(await db.query<{id:string}>("select id from public.services where clinic_id=$1 limit 1",[ids.a])).rows[0].id;
 f.doctor=(await db.query<{id:string}>("select id from public.doctor_locations where clinic_id=$1 limit 1",[ids.a])).rows[0].id;
 f.type=(await db.query<{id:string}>("select id from public.document_types where clinic_id=$1 and code='result'",[ids.a])).rows[0].id;
 f.appointment=(await db.query<{id:string}>(`insert into public.appointments(organization_id,clinic_id,patient_id,service_id,doctor_location_id,start_at,end_at,occupied_start_at,occupied_end_at,duration_minutes,buffer_before,buffer_after,created_by) values($1,$2,$3,$4,$5,'2027-05-10T09:00:00Z','2027-05-10T09:30:00Z','2027-05-10T08:55:00Z','2027-05-10T09:35:00Z',30,5,5,$6) returning id`,[ids.org,ids.a,f.patient,f.service,f.doctor,ids.owner])).rows[0].id;
 await db.query("insert into auth.users(id,email) values($1,'portal-a@example.test'),($2,'portal-b@example.test')",[patientUser,otherPatientUser]);
 await one(ids.owner,"public.link_patient_identity($1,$2,$3)",[ids.a,f.patient,patientUser]);await one(ids.owner,"public.link_patient_identity($1,$2,$3)",[ids.a,f.otherPatient,otherPatientUser]);
});
afterAll(async()=>db.close());

describe("confirmation tokens and notification jobs",()=>{
 it("stores only a digest and confirms without exposing portal access",async()=>{const digest="a".repeat(64),publicId="90000000-0000-4000-8000-000000000001";await one(ids.reception,"public.issue_appointment_confirmation($1,$2,$3,$4,now()+interval '7 days')",[ids.a,f.appointment,digest,publicId]);const stored=(await db.query<{token_hash:string}>("select token_hash from public.appointment_confirmations where appointment_id=$1 and revoked_at is null",[f.appointment])).rows[0];expect(stored.token_hash).toBe(digest);expect(JSON.stringify(stored)).not.toContain(publicId+".");const details=await anon<Record<string,unknown>|null>("public.public_confirmation_details($1,$2)",[digest,"b".repeat(64)]);expect(details?.clinic_name).toBe("Clinic A");const action=await anon<{status:string}>("public.public_confirmation_action($1,'confirm',$2)",[digest,"c".repeat(64)]);expect(action.status).toBe("CONFIRMED");expect((await db.query<{status:string}>("select status from public.appointments where id=$1",[f.appointment])).rows[0].status).toBe("CONFIRMED");});
 it("rejects expired and revoked tokens",async()=>{const old="d".repeat(64);await one(ids.owner,"public.issue_appointment_confirmation($1,$2,$3,$4,now()+interval '1 day')",[ids.a,f.appointment,old,"90000000-0000-4000-8000-000000000002"]);await db.query("update public.appointment_confirmations set expires_at=now()-interval '1 minute' where token_hash=$1",[old]);expect(await anon("public.public_confirmation_details($1,$2)",[old,"e".repeat(64)])).toBeNull();const fresh="f".repeat(64);await one(ids.owner,"public.issue_appointment_confirmation($1,$2,$3,$4,now()+interval '1 day')",[ids.a,f.appointment,fresh,"90000000-0000-4000-8000-000000000003"]);await db.query("update public.appointment_confirmations set revoked_at=now() where token_hash=$1",[fresh]);expect(await anon("public.public_confirmation_details($1,$2)",[fresh,"1".repeat(64)])).toBeNull();});
 it("claims reminder work idempotently and never duplicates a job",async()=>{await db.query("update public.appointments set start_at=now()+interval '2 hours',end_at=now()+interval '2 hours 30 minutes',occupied_start_at=now()+interval '115 minutes',occupied_end_at=now()+interval '155 minutes' where id=$1",[f.appointment]);async function worker<T>(sql:string,args:unknown[]=[]){return db.transaction(async tx=>{await tx.exec("set local role service_role");await tx.query("select set_config('request.jwt.claim.role','service_role',true)");return tx.query<T>(sql,args);});}await worker("select public.enqueue_due_reminders(now())");await worker("select public.enqueue_due_reminders(now())");expect((await db.query("select id from public.notification_jobs where appointment_id=$1 and event='APPOINTMENT_REMINDER'",[f.appointment])).rows).toHaveLength(1);const claimed=await worker<{jobs:unknown[]}>("select public.claim_notification_jobs(100) jobs");expect(claimed.rows[0].jobs).toBeTruthy();});
});

describe("patient documents, results and IDOR boundaries",()=>{
 it("authorizes only the linked patient and rejects cross-patient/cross-clinic IDs",async()=>{f.document=await one(ids.reception,"public.save_patient_document($1,$2,null,$3,'Analiză externă',$4,'analiza.pdf','application/pdf',1200,true)",[ids.a,f.patient,f.type,`${ids.a}/${f.patient}/documents/file.pdf`]);expect((await one<Record<string,string>>(patientUser,"public.authorize_document_download($1,$2)",[ids.a,f.document])).path).toContain(f.patient);await expect(one(otherPatientUser,"public.authorize_document_download($1,$2)",[ids.a,f.document])).rejects.toThrow("Access denied");await expect(one(patientUser,"public.list_patient_documents($1,$2)",[ids.b,f.clinicBPatient])).rejects.toThrow("Access denied");});
 it("hides DRAFT and VALIDATED results, then exposes only RELEASED",async()=>{f.result=await one(ids.doctor,"public.save_medical_result($1,null,$2,$3,'Raport clinic','Conținut medical verificat',null,'')",[ids.a,f.appointment,f.doctor]);await expect(one(patientUser,"public.read_medical_result($1,$2)",[ids.a,f.result])).rejects.toThrow("Access denied");await one(ids.doctor,"public.transition_medical_result($1,$2,'VALIDATED',null)",[ids.a,f.result]);await expect(one(patientUser,"public.read_medical_result($1,$2)",[ids.a,f.result])).rejects.toThrow("Access denied");const path=`${ids.a}/${f.patient}/results/${f.result}/v3.pdf`;await one(ids.doctor,"public.transition_medical_result($1,$2,'RELEASED',$3)",[ids.a,f.result,path]);const released=await one<{status:string}>(patientUser,"public.read_medical_result($1,$2)",[ids.a,f.result]);expect(released.status).toBe("RELEASED");await expect(one(otherPatientUser,"public.authorize_result_download($1,$2)",[ids.a,f.result])).rejects.toThrow("Access denied");expect((await one<Record<string,string>>(patientUser,"public.authorize_result_download($1,$2)",[ids.a,f.result])).path).toBe(path);const portal=await one<{results:{id:string}[]}>(patientUser,"public.patient_portal_home()");expect(portal.results.map(x=>x.id)).toContain(f.result);});
 it("keeps a complete result version trail without medical text in audit metadata",async()=>{const versions=await db.query<{status:string}>("select status from public.medical_result_versions where result_id=$1 order by version",[f.result]);expect(versions.rows.map(x=>x.status)).toEqual(["DRAFT","VALIDATED","RELEASED"]);const audit=await db.query("select metadata from public.audit_logs where entity='medical_results' and entity_id=$1",[f.result]);expect(JSON.stringify(audit.rows)).not.toContain("Conținut medical verificat");});
 it("blocks anonymous portal calls and uses one-minute signed downloads",async()=>{await expect(anon("public.patient_portal_home()" )).rejects.toThrow();expect(SIGNED_DOWNLOAD_TTL_SECONDS).toBe(60);});
});
