import { T } from "@/components/locale-provider";
import { z } from "zod";
import { requireClinic } from "@/features/auth/access";
import { can } from "@/lib/permissions";
import { Section } from "@/components/ui/page";
import { ActionForm } from "@/components/ui/action-form";
import { Field, Input, Select } from "@/components/ui/form";
import { saveDoctorCredentials } from "./actions";
export async function DoctorCredentials({cid,did}:{cid:string;did:string}){const {client,permissions}=await requireClinic(cid,"catalog.read");const [{data:raw},{data:members}]=await Promise.all([client.rpc("read_doctor_credentials",{cid,did}),client.from("clinic_memberships").select("user_id").eq("clinic_id",cid).eq("role","DOCTOR").eq("active",true)]);const credential=z.object({staff_user_id:z.string().nullable().optional(),signature_object_path:z.string().nullable().optional(),stamp_object_path:z.string().nullable().optional()}).parse(raw);const ids=members?.map(m=>m.user_id)??[];const {data:profiles}=ids.length?await client.from("profiles").select("id,full_name").in("id",ids):{data:[]};return <Section title="Semnătură și parafă" description="Imagini scanate păstrate privat. Acestea nu reprezintă o semnătură electronică calificată.">{can(permissions,"credentials.manage")?<ActionForm action={saveDoctorCredentials.bind(null,cid,did)}><Field label="Contul medicului"><Select name="staff_user_id" defaultValue={credential.staff_user_id??""}><option value=""><T>{"Neasociat"}</T></option>{profiles?.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</Select></Field><Field label="Semnătură scanată"><Input name="signature" type="file" accept="image/png,image/jpeg,image/webp"/><small><T>{credential.signature_object_path?"Fișier configurat":"Niciun fișier"}</T></small></Field><Field label="Parafă scanată"><Input name="stamp" type="file" accept="image/png,image/jpeg,image/webp"/><small><T>{credential.stamp_object_path?"Fișier configurat":"Niciun fișier"}</T></small></Field></ActionForm>:<p className="muted"><T>{"Configurarea este disponibilă medicului asociat sau administratorului."}</T></p>}</Section>}
