"use client";
import { T } from "@/components/locale-provider";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Field, Input, Select } from "@/components/ui/form";
import { persistSetup, completeSetup } from "./actions";
import { defaultHours, steps, validateStep, validateSetup, type OnboardingDraft } from "./model";

const days = ["Luni", "Marți", "Miercuri", "Joi", "Vineri", "Sâmbătă", "Duminică"];
const visibleSteps = [1, 3, 4, 5, 6, 7, 8];
export function SetupWizard({ organizationId, initial, initialStep, initialRevision }: { organizationId: string; initial: OnboardingDraft; initialStep: number; initialRevision: number }) {
  const [draft, setDraft] = useState(initial);
  const [step, setStep] = useState(initialStep === 2 ? 1 : initialStep);
  const [revision, setRevision] = useState(initialRevision);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [completed, setCompleted] = useState<{ clinicId: string; invitations: { email: string; url: string; delivery: string }[] } | null>(null);
  const text = (label: string, value: string, update: (value: string) => void, type = "text", maxLength = 160) => <Field label={label}><Input type={type} value={value} maxLength={maxLength} onChange={(e) => { setMessage(""); update(e.target.value); }}/></Field>;
  const location = (value: string, update: (value: string) => void) => <Field label="Locație"><Select value={value} onChange={(e) => update(e.target.value)}>{draft.locations.map((l) => <option key={l.id} value={l.id}>{l.name || "Locație fără denumire"}</option>)}</Select></Field>;
  const updateRow = <K extends "locations" | "services" | "doctors" | "rooms" | "team">(key: K, index: number, value: Partial<OnboardingDraft[K][number]>) => setDraft((old) => ({ ...old, [key]: old[key].map((item, i) => i === index ? { ...item, ...value } : item) }));
  const remove = (key: "services" | "doctors" | "rooms" | "team", index: number) => setDraft((old) => ({ ...old, [key]: old[key].filter((_, i) => i !== index) }));
  async function navigate(next: number, finish = false) {
    if (pending) return;
    const currentStepError = validateStep(draft, step) ?? (step === 1 ? validateStep(draft, 2) : null);
    const validation = finish ? validateSetup(draft) : next > step ? currentStepError : null;
    if (validation) { setError(validation); return; }
    setPending(true); setError(""); setMessage("");
    try {
      if (finish) {
        const result = await completeSetup(organizationId, draft, revision);
        if (result.revision !== undefined) setRevision(result.revision);
        if (result.error) setError(result.error);
        else if ("clinicId" in result && result.clinicId) setCompleted({ clinicId: result.clinicId, invitations: result.invitations });
      } else {
        const result = await persistSetup(organizationId, draft, next, revision, step);
        if (result.error) setError(result.error);
        else if (result.revision !== undefined) { setRevision(result.revision); setStep(next); setMessage("Progresul a fost salvat."); }
      }
    } catch { setError("Conexiunea nu a putut fi finalizată. Reîncărcați pagina pentru a verifica progresul salvat."); }
    finally { setPending(false); }
  }
  const displayStep = visibleSteps.indexOf(step) + 1;
  if (completed) return <section className="surface setup-content"><p className="eyebrow"><T>{"CONFIGURARE FINALIZATĂ"}</T></p><h1>{draft.clinic.name}</h1><p><T>{"Locațiile, programul și resursele au fost salvate. Perioada de probă este de 30 de zile."}</T></p>{completed.invitations.length > 0 && <><h2><T>{"Invitațiile echipei"}</T></h2><p className="muted"><T>{"Verificați starea livrării pentru fiecare coleg. Linkurile expiră după 7 zile; puteți genera altele din Echipă și acces."}</T></p>{completed.invitations.map((invite) => <Field key={invite.email} label={invite.email}><Input readOnly value={invite.url} onFocus={(e) => e.target.select()}/><small>{invite.delivery}</small></Field>)}</>}<Button asChild><Link href={`/clinics/${completed.clinicId}`}><T>{"Intră în spațiul de lucru"}</T></Link></Button></section>;
  return <div className="setup-workspace">
    <aside className="setup-progress"><p className="eyebrow"><T>{"SPAȚIUL CLINICII"}</T></p><h2><T>{"Configurare"}</T></h2><p className="muted"><T>{"Pasul "}</T>{displayStep}<T>{" din 7"}</T></p><ol>{visibleSteps.map((setupStep, i) => <li key={setupStep}><button disabled={pending || setupStep > step} aria-current={step === setupStep ? "step" : undefined} onClick={() => void navigate(setupStep)}><span>{setupStep < step ? "✓" : i + 1}</span><T>{setupStep === 1 ? "Clinică și locații" : steps[setupStep - 1]}</T></button></li>)}</ol><p className="muted"><T>{"Progresul se păstrează la fiecare pas și prin „Salvează progresul”."}</T></p></aside>
    <section className="surface setup-content"><p className="eyebrow"><T>{"PASUL "}</T>{displayStep} / 7</p><h1><T>{steps[step - 1]}</T></h1>
      <form onSubmit={(e) => { e.preventDefault(); void navigate(step === 1 ? 3 : Math.min(step + 1, 8), step === 8); }} className="form-stack">
        <fieldset disabled={pending}>
          {step === 1 && <>
            <div className="setup-fields">{text("Denumirea clinicii", draft.clinic.name, (name) => setDraft({ ...draft, clinic: { ...draft.clinic, name } }), "text", 100)}{text("Denumire juridică (opțional)", draft.clinic.legal_name, (legal_name) => setDraft({ ...draft, clinic: { ...draft.clinic, legal_name } }))}{text("CUI (opțional)", draft.clinic.cui, (cui) => setDraft({ ...draft, clinic: { ...draft.clinic, cui } }), "text", 30)}{text("Telefon", draft.clinic.phone, (phone) => setDraft({ ...draft, clinic: { ...draft.clinic, phone } }), "tel", 40)}{text("Email clinică", draft.clinic.email, (email) => setDraft({ ...draft, clinic: { ...draft.clinic, email } }), "email", 254)}{text("Website (opțional)", draft.clinic.website, (website) => setDraft({ ...draft, clinic: { ...draft.clinic, website } }), "url", 500)}{text("Specialitate", draft.clinic.specialty, (specialty) => setDraft({ ...draft, clinic: { ...draft.clinic, specialty } }), "text", 120)}</div>
            <section className="setup-location-section"><h2><T>{"Locații"}</T></h2><p className="muted"><T>{"Prima locație va fi locația implicită. Accesul echipei se acordă separat pentru fiecare locație."}</T></p>{draft.locations.map((l, i) => <div className="setup-record" key={l.id}><h3><T>{"Locația "}</T>{i + 1}</h3><div className="setup-fields">{text("Denumire locație", l.name, (name) => updateRow("locations", i, { name }), "text", 100)}{text("Adresă", l.address, (address) => updateRow("locations", i, { address }), "text", 250)}{text("Oraș", l.city, (city) => updateRow("locations", i, { city }), "text", 100)}{text("Județ", l.county, (county) => updateRow("locations", i, { county }), "text", 100)}{text("Telefon locație", l.phone, (phone) => updateRow("locations", i, { phone }), "tel", 40)}{text("Email locație", l.email, (email) => updateRow("locations", i, { email }), "email", 254)}</div>{i > 0 && <Button type="button" variant="ghost" onClick={() => { if (draft.services.some((s) => s.location_id === l.id) || draft.doctors.some((d) => d.location_ids.includes(l.id)) || draft.rooms.some((r) => r.location_id === l.id) || draft.team.some((t) => t.location_id === l.id)) { setError("Eliminați mai întâi resursele atribuite acestei locații."); return; } setDraft({ ...draft, locations: draft.locations.filter((v) => v.id !== l.id) }); }}><T>{"Elimină locația"}</T></Button>}</div>)}<Button type="button" variant="outline" disabled={draft.locations.length >= 20} onClick={() => setDraft({ ...draft, locations: [...draft.locations, { id: crypto.randomUUID(), name: "", address: "", city: "", county: "", phone: "", email: "", hours: defaultHours() }] })}><T>{"Adaugă locație"}</T></Button></section>
          </>}
          {step === 3 && <><p className="muted"><T>{"Programul medicilor și cabinetelor va porni de la aceste intervale. Îl puteți personaliza ulterior în Disponibilitate, inclusiv pauze și concedii."}</T></p>{draft.locations.map((l, i) => <div className="setup-record" key={l.id}><h3>{l.name}</h3><div className="schedule-editor">{l.hours.map((h, j) => <div className="schedule-editor-row" key={h.weekday}><label><input type="checkbox" checked={!h.closed} onChange={(e) => updateRow("locations", i, { hours: l.hours.map((v, k) => k === j ? { ...v, closed: !e.target.checked } : v) })}/>{days[h.weekday - 1]}</label><Input aria-label={`Deschidere ${days[j]} ${l.name}`} type="time" value={h.start_time} disabled={h.closed} onChange={(e) => updateRow("locations", i, { hours: l.hours.map((v, k) => k === j ? { ...v, start_time: e.target.value } : v) })}/><span>–</span><Input aria-label={`Închidere ${days[j]} ${l.name}`} type="time" value={h.end_time} disabled={h.closed} onChange={(e) => updateRow("locations", i, { hours: l.hours.map((v, k) => k === j ? { ...v, end_time: e.target.value } : v) })}/></div>)}</div></div>)}</>}
          {step === 4 && <>{!draft.services.length && <p className="muted"><T>{"Adăugați serviciile reale ale clinicii."}</T></p>}{draft.services.map((s, i) => <div className="setup-record" key={s.id}><h3><T>{"Serviciul "}</T>{i + 1}</h3><div className="setup-fields">{text("Denumire serviciu", s.name, (name) => updateRow("services", i, { name }))}{location(s.location_id, (location_id) => updateRow("services", i, { location_id }))}{text("Descriere", s.description, (description) => updateRow("services", i, { description }), "text", 2000)}{text("Preț (RON)", s.price, (price) => updateRow("services", i, { price }))}<Field label="Durată (minute)"><Input type="number" min={5} max={1440} value={s.duration_minutes} onChange={(e) => updateRow("services", i, { duration_minutes: Number(e.target.value) })}/></Field></div><Button type="button" variant="ghost" onClick={() => { remove("services", i); setDraft((old) => ({ ...old, doctors: old.doctors.map((d) => ({ ...d, service_ids: d.service_ids.filter((id) => id !== s.id) })) })); }}><T>{"Elimină serviciul"}</T></Button></div>)}<Button type="button" variant="outline" disabled={draft.services.length >= 200} onClick={() => setDraft({ ...draft, services: [...draft.services, { id: crypto.randomUUID(), location_id: draft.locations[0].id, name: "", description: "", price: "", duration_minutes: 30 }] })}><T>{"Adaugă serviciu"}</T></Button></>}
          {step === 5 && <><p className="muted"><T>{"Medicii pot exista fără cont Voxa. Codul intern generat nu reprezintă o acreditare medicală."}</T></p>{draft.doctors.map((d, i) => <div className="setup-record" key={d.id}><h3><T>{"Medicul "}</T>{i + 1}</h3><div className="setup-fields">{text("Prenume", d.first_name, (first_name) => updateRow("doctors", i, { first_name }), "text", 80)}{text("Nume", d.last_name, (last_name) => updateRow("doctors", i, { last_name }), "text", 80)}{text("Specialitate medic", d.specialty, (specialty) => updateRow("doctors", i, { specialty }), "text", 120)}{text("Cod profesional (opțional)", d.professional_code, (professional_code) => updateRow("doctors", i, { professional_code }), "text", 60)}{text("Email medic", d.email, (email) => updateRow("doctors", i, { email }), "email", 254)}{text("Telefon medic", d.phone, (phone) => updateRow("doctors", i, { phone }), "tel", 40)}{text("Culoare calendar", d.color, (color) => updateRow("doctors", i, { color }), "color")}</div><fieldset className="setup-choices"><legend><T>{"Locații atribuite"}</T></legend>{draft.locations.map((l) => <label key={l.id}><input type="checkbox" checked={d.location_ids.includes(l.id)} onChange={(e) => updateRow("doctors", i, { location_ids: e.target.checked ? [...d.location_ids, l.id] : d.location_ids.filter((id) => id !== l.id) })}/>{l.name}</label>)}</fieldset><fieldset className="setup-choices"><legend><T>{"Servicii oferite"}</T></legend>{draft.services.filter((s) => d.location_ids.includes(s.location_id)).map((s) => <label key={s.id}><input type="checkbox" checked={d.service_ids.includes(s.id)} onChange={(e) => updateRow("doctors", i, { service_ids: e.target.checked ? [...d.service_ids, s.id] : d.service_ids.filter((id) => id !== s.id) })}/>{s.name} · {draft.locations.find((l) => l.id === s.location_id)?.name}</label>)}</fieldset><Button type="button" variant="ghost" onClick={() => remove("doctors", i)}><T>{"Elimină medicul"}</T></Button></div>)}<Button type="button" variant="outline" disabled={draft.doctors.length >= 100} onClick={() => setDraft({ ...draft, doctors: [...draft.doctors, { id: crypto.randomUUID(), first_name: "", last_name: "", specialty: "", professional_code: "", email: "", phone: "", color: "#397766", location_ids: [draft.locations[0].id], service_ids: [] }] })}><T>{"Adaugă medic"}</T></Button><p className="muted"><T>{"Cabinetele și invitațiile echipei pot fi adăugate oricând din setări."}</T></p></>}
          {step === 6 && <><p className="muted"><T>{"Cabinetele sunt opționale. Ulterior puteți configura serviciile care necesită un cabinet."}</T></p>{draft.rooms.map((r, i) => <div className="setup-record" key={r.id}><div className="setup-fields">{text("Denumire cabinet", r.name, (name) => updateRow("rooms", i, { name }), "text", 120)}{location(r.location_id, (location_id) => updateRow("rooms", i, { location_id }))}{text("Descriere cabinet", r.description, (description) => updateRow("rooms", i, { description }), "text", 100)}</div><Button type="button" variant="ghost" onClick={() => remove("rooms", i)}><T>{"Elimină cabinetul"}</T></Button></div>)}<Button type="button" variant="outline" disabled={draft.rooms.length >= 100} onClick={() => setDraft({ ...draft, rooms: [...draft.rooms, { id: crypto.randomUUID(), location_id: draft.locations[0].id, name: "", description: "" }] })}><T>{"Adaugă cabinet"}</T></Button></>}
          {step === 7 && <><p className="muted"><T>{"Opțional. La finalizare primiți linkuri securizate și starea livrării. Dacă serviciul de email nu este configurat, trimiteți linkurile manual pentru staging. Medicii invitați trebuie asociați resursei profesionale din profilul medicului."}</T></p>{draft.team.map((t, i) => <div className="setup-record" key={t.id}><div className="setup-fields">{text("Email coleg", t.email, (email) => updateRow("team", i, { email }), "email", 254)}{location(t.location_id, (location_id) => updateRow("team", i, { location_id }))}<Field label="Rol coleg"><Select value={t.role} onChange={(e) => updateRow("team", i, { role: e.target.value as typeof t.role })}><option value="ADMIN"><T>{"Administrator"}</T></option><option value="RECEPTION"><T>{"Recepție"}</T></option><option value="DOCTOR"><T>{"Medic"}</T></option></Select></Field></div><Button type="button" variant="ghost" onClick={() => remove("team", i)}><T>{"Elimină invitația"}</T></Button></div>)}<Button type="button" variant="outline" disabled={draft.team.length >= 30} onClick={() => setDraft({ ...draft, team: [...draft.team, { id: crypto.randomUUID(), location_id: draft.locations[0].id, email: "", role: "RECEPTION" }] })}><T>{"Adaugă coleg"}</T></Button></>}
          {step === 8 && <><h2>{draft.clinic.name}</h2><dl className="record-details"><div><dt><T>{"Locații"}</T></dt><dd>{draft.locations.length}</dd></div><div><dt><T>{"Servicii"}</T></dt><dd>{draft.services.length}</dd></div><div><dt><T>{"Medici"}</T></dt><dd>{draft.doctors.length}</dd></div><div><dt><T>{"Cabinete"}</T></dt><dd>{draft.rooms.length}</dd></div><div><dt><T>{"Invitații"}</T></dt><dd>{draft.team.length}</dd></div><div><dt><T>{"Program"}</T></dt><dd>{draft.locations.map((l) => `${l.name}: ${l.hours.filter((h) => !h.closed).length} zile deschise`).join(" · ")}</dd></div></dl><p className="muted"><T>{"Ora locală: Europe/Bucharest · Monedă: RON. Toate datele se salvează împreună la finalizare. Programul inițial al medicilor și cabinetelor urmează locația."}</T></p></>}
        </fieldset>
        {error && <p className="message error" role="alert"><T>{error}</T></p>}{message && <p className="message success" role="status"><T>{message}</T></p>}
        <div className="setup-actions"><Button type="button" variant="ghost" disabled={pending || step === 1} onClick={() => void navigate(step === 3 ? 1 : step - 1)}><T>{"Înapoi"}</T></Button><Button type="button" variant="outline" disabled={pending} onClick={() => void navigate(step)}><T>{"Salvează progresul"}</T></Button>{step === 5 && <Button type="button" disabled={pending} onClick={() => void navigate(step, true)}><T>{"Finalizează acum"}</T></Button>}<Button variant={step === 5 ? "outline" : undefined} disabled={pending}><T>{pending ? "Se salvează…" : step === 8 ? "Finalizează configurarea" : "Continuă"}</T></Button></div>
      </form>
    </section>
  </div>;
}
